<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "content_wrapper"
 *
 * Auto generated by Extension Builder 2020-05-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Content Wrapper',
    'description' => 'Own Css Classes for every content element',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => '',
    'state' => 'beta',
    'version' => '3.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '13.4.0-14.3.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
